name: Generate Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate documentation
      run: npm run docs:generate
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit documentation changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/API.md
        git commit -m "docs: auto-generate API documentation [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "docs: auto-generate API documentation"
        title: "Auto-generated API documentation"
        body: |
          This PR contains automatically generated API documentation updates.
          
          **Changes:**
          - Updated `docs/API.md` with latest JSDoc comments
          
          **Generated by:** GitHub Action on ${{ github.event.head_commit.timestamp }}
        branch: auto-docs-update
        delete-branch: true
